version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "01:00"
    timezone: Europe/Athens
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.google.auto.value:auto-value
    versions:
    - "> 1.3"
  - dependency-name: org.glassfish.jersey.connectors:jersey-apache-connector
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.glassfish.jersey.core:jersey-client
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.glassfish.jersey.inject:jersey-hk2
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.glassfish.jersey.media:jersey-media-json-jackson
    versions:
    - ">= 3.a, < 4"
  - dependency-name: org.hamcrest:hamcrest-library
    versions:
    - "> 1.3"
  - dependency-name: org.immutables:value
    versions:
    - "> 2.8.8, < 2.9"
  - dependency-name: com.google.auth:google-auth-library-oauth2-http
    versions:
    - 0.25.0
    - 0.25.4
